#!/usr/bin/env python3
"""
One-terminal 3-arm touch calibration.

Run all arms in command mode (mode=1, auto_enable=true). This script:
  1. controls one active arm at a time with keyboard Cartesian jogs,
  2. records MID/LEFT/RIGHT tip positions for each shared physical point,
  3. resets each arm after recording to reduce collision risk,
  4. fits LEFT->MID and RIGHT->MID rigid transforms with SVD.
"""
import argparse
import json
import math
import os
import select
import sys
import termios
import time
import tty
from datetime import datetime

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

# Import this before rospy; it loads casadi/pinocchio and avoids libstdc++ issues.
from eef_keyboard_control_singlearm import PinocchioIKSolver  # noqa: E402

import pinocchio as pin  # noqa: E402
import rospy  # noqa: E402
from geometry_msgs.msg import PoseStamped  # noqa: E402
from sensor_msgs.msg import JointState  # noqa: E402
from std_msgs.msg import Header  # noqa: E402
from tf.transformations import (  # noqa: E402
    euler_from_matrix,
    euler_matrix,
    quaternion_matrix,
)


ARMS = ("mid", "left", "right")
JOINT_NAMES = ["joint0", "joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
INITIAL_ARM_JOINTS = (0.0463, 0.5300, -0.5562, 0.0000, 0.6500, 0.0000)
INITIAL_GRIPPER = 0.1


def pose_to_tcp_xyz(msg, tcp_offset):
    p = msg.pose.position
    q = msg.pose.orientation
    T = quaternion_matrix([q.x, q.y, q.z, q.w])
    xyz = np.array([p.x, p.y, p.z], dtype=float)
    return xyz + T[:3, :3] @ np.asarray(tcp_offset, dtype=float)


def fit_rigid_transform(src_points, dst_points):
    """Return R, t, errors for dst ~= R @ src + t."""
    src = np.asarray(src_points, dtype=float)
    dst = np.asarray(dst_points, dtype=float)
    src_c = src.mean(axis=0)
    dst_c = dst.mean(axis=0)
    X = src - src_c
    Y = dst - dst_c
    H = X.T @ Y
    U, _, Vt = np.linalg.svd(H)
    R = Vt.T @ U.T
    if np.linalg.det(R) < 0.0:
        Vt[-1, :] *= -1.0
        R = Vt.T @ U.T
    t = dst_c - R @ src_c
    pred = (R @ src.T).T + t
    err = np.linalg.norm(pred - dst, axis=1)
    return R, t, err


def transform_to_dict(R, t):
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = t
    rpy = np.asarray(euler_from_matrix(T), dtype=float)
    return {
        "xyz": [float(x) for x in t],
        "rpy": [float(x) for x in rpy],
        "matrix": [[float(x) for x in row] for row in T],
    }


def write_yaml(path, result):
    def vec(v):
        return "[" + ", ".join(f"{float(x):.9f}" for x in v) + "]"

    lines = [
        "# Generated by calibrate_3arm_touch_control.py",
        f"created_at: {result['created_at']}",
        "world_frame: mid_base",
        "source: controlled_touch_point_svd",
        f"num_points: {result['num_points']}",
        f"tcp_offset: {vec(result['tcp_offset'])}",
        "transforms:",
    ]
    for arm in ARMS:
        tr = result["transforms"][arm]
        lines += [
            f"  {arm}:",
            "    parent: mid_base",
            f"    child: {arm}_base",
            f"    xyz: {vec(tr['xyz'])}",
            f"    rpy: {vec(tr['rpy'])}",
            "    matrix:",
        ]
        for row in tr["matrix"]:
            lines.append(f"      - {vec(row)}")
    lines += [
        "errors_m:",
        f"  left_to_mid: {vec(result['errors_m']['left_to_mid'])}",
        f"  right_to_mid: {vec(result['errors_m']['right_to_mid'])}",
        "summary_m:",
    ]
    for name, stats in result["summary_m"].items():
        lines += [
            f"  {name}:",
            f"    mean: {stats['mean']:.9f}",
            f"    rms: {stats['rms']:.9f}",
            f"    max: {stats['max']:.9f}",
        ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


class RawKeyboard:
    def __enter__(self):
        self.fd = sys.stdin.fileno()
        self.old = termios.tcgetattr(self.fd)
        tty.setcbreak(self.fd)
        return self

    def __exit__(self, exc_type, exc, tb):
        termios.tcsetattr(self.fd, termios.TCSADRAIN, self.old)

    def read_key(self, timeout=0.05):
        ready, _, _ = select.select([sys.stdin], [], [], timeout)
        if not ready:
            return None
        return sys.stdin.read(1)


class ControlledTouchCalibrator:
    def __init__(self, args):
        self.args = args
        rospy.init_node("calibrate_3arm_touch_control", anonymous=True)
        self.ik = PinocchioIKSolver(args.urdf)
        self.joint = {arm: None for arm in ARMS}
        self.pose = {arm: None for arm in ARMS}
        self.pub = {}
        for arm in ARMS:
            rospy.Subscriber(
                f"/puppet/joint_{arm}",
                JointState,
                self._make_joint_cb(arm),
                queue_size=50,
                tcp_nodelay=True,
            )
            rospy.Subscriber(
                f"/puppet/end_pose_{arm}",
                PoseStamped,
                self._make_pose_cb(arm),
                queue_size=50,
                tcp_nodelay=True,
            )
            self.pub[arm] = rospy.Publisher(
                f"/master/joint_{arm}",
                JointState,
                queue_size=10,
            )

        self.points = {arm: [] for arm in ARMS}
        self.active_arm = None
        self.target_xyz = None
        self.target_rpy = None
        self.target_q = None
        self.gripper = args.gripper
        self.pos_step = args.pos_step
        self.rpy_step = args.rpy_step

    def _make_joint_cb(self, arm):
        def cb(msg):
            self.joint[arm] = msg
        return cb

    def _make_pose_cb(self, arm):
        def cb(msg):
            self.pose[arm] = msg
        return cb

    def wait_feedback(self):
        deadline = rospy.Time.now() + rospy.Duration(self.args.feedback_wait)
        rate = rospy.Rate(20)
        while not rospy.is_shutdown():
            ready = all(
                self.joint[a] is not None
                and len(self.joint[a].position) >= 7
                and self.pose[a] is not None
                for a in ARMS
            )
            if ready:
                return True
            if rospy.Time.now() > deadline:
                return False
            rate.sleep()
        return False

    def publish(self, arm, q7):
        msg = JointState()
        msg.header = Header(stamp=rospy.Time.now())
        msg.name = JOINT_NAMES
        msg.position = list(q7)
        self.pub[arm].publish(msg)

    def fk(self, q6):
        q = np.asarray(q6, dtype=float)
        pin.framesForwardKinematics(self.ik.model, self.ik.data, q)
        se3 = self.ik.data.oMf[self.ik.ee_frame_id]
        xyz = np.asarray(se3.translation, dtype=float).flatten()
        rpy = np.asarray(euler_from_matrix(se3.rotation), dtype=float)
        return xyz, rpy

    def set_active_arm_from_feedback(self, arm):
        self.active_arm = arm
        q6 = np.asarray(self.joint[arm].position[:6], dtype=float)
        self.target_xyz, self.target_rpy = self.fk(q6)
        self.target_q = np.asarray(self.joint[arm].position[:7], dtype=float)
        self.gripper = float(self.target_q[6])
        self.ik.init_data = q6.copy()
        self.ik.history_data = q6.copy()

    def solve_and_publish_target(self):
        seed = self.target_q[:6] if self.target_q is not None else None
        sol6, ok, msg = self.ik.solve(
            self.target_xyz,
            self.target_rpy,
            gripper=self.gripper,
            motorstate=seed,
        )
        if not ok:
            print(f"\n[ctrl] IK failed: {msg}")
            return False
        self.target_q = np.asarray(list(sol6) + [self.gripper], dtype=float)
        self.publish(self.active_arm, self.target_q)
        return True

    def ramp_arm(self, arm, target7, label):
        current = np.asarray(self.joint[arm].position[:7], dtype=float)
        target = np.asarray(target7, dtype=float)
        max_delta = float(np.max(np.abs(target[:6] - current[:6])))
        duration = max(max_delta / self.args.ramp_speed_rad_s, self.args.min_ramp_sec)
        steps = max(1, int(duration * self.args.hz))
        rate = rospy.Rate(self.args.hz)
        print(f"\n[ctrl] {arm} {label}: ramp {duration:.2f}s, max_delta={max_delta:.3f} rad")
        for i in range(steps):
            if rospy.is_shutdown():
                return False
            alpha = float(i + 1) / float(steps)
            q = (1.0 - alpha) * current + alpha * target
            self.publish(arm, q)
            rate.sleep()
        for _ in range(max(1, int(self.args.hold_sec * self.args.hz))):
            if rospy.is_shutdown():
                return False
            self.publish(arm, target)
            rate.sleep()
        return True

    def reset_arm(self, arm):
        reset7 = np.asarray(list(INITIAL_ARM_JOINTS) + [self.args.gripper], dtype=float)
        ok = self.ramp_arm(arm, reset7, "reset")
        if ok:
            self.target_q = reset7.copy()
            self.target_xyz, self.target_rpy = self.fk(reset7[:6])
        return ok

    def sample_tcp(self, arm):
        samples = []
        for _ in range(self.args.samples):
            msg = self.pose[arm]
            if msg is not None:
                samples.append(pose_to_tcp_xyz(msg, self.args.tcp_offset))
            time.sleep(self.args.sample_dt)
        arr = np.vstack(samples)
        return arr.mean(axis=0), arr.std(axis=0)

    def print_help(self):
        print(
            "\nControls:\n"
            "  w/s : x + / -   (forward/back)\n"
            "  a/d : y + / -   (left/right)\n"
            "  r/f : z + / -   (up/down)\n"
            "  u/o : roll - / +\n"
            "  i/k : pitch + / -\n"
            "  j/l : yaw   + / -\n"
            "  [/] : gripper - / +\n"
            "  1/2/3 : xyz step = 1 / 5 / 10 mm\n"
            "  4/5/6 : rpy step = 0.5 / 1 / 3 deg\n"
            "  h : reset current arm\n"
            "  SPACE : record current arm touch point, then reset and advance\n"
            "  ? : show controls\n"
            "  q : quit\n"
        )

    def handle_key(self, key):
        if key is None:
            return "none"
        if key == "q":
            return "quit"
        if key == "?":
            self.print_help()
            return "none"
        if key == "1":
            self.pos_step = 0.001
            print("\n[ctrl] xyz step = 1 mm")
            return "none"
        if key == "2":
            self.pos_step = 0.005
            print("\n[ctrl] xyz step = 5 mm")
            return "none"
        if key == "3":
            self.pos_step = 0.010
            print("\n[ctrl] xyz step = 10 mm")
            return "none"
        if key == "4":
            self.rpy_step = math.radians(0.5)
            print("\n[ctrl] rpy step = 0.5 deg")
            return "none"
        if key == "5":
            self.rpy_step = math.radians(1.0)
            print("\n[ctrl] rpy step = 1 deg")
            return "none"
        if key == "6":
            self.rpy_step = math.radians(3.0)
            print("\n[ctrl] rpy step = 3 deg")
            return "none"
        if key == "h":
            self.reset_arm(self.active_arm)
            self.set_active_arm_from_feedback(self.active_arm)
            return "none"
        if key == " ":
            return "record"

        moved = False
        if key == "w":
            self.target_xyz[0] += self.pos_step
            moved = True
        elif key == "s":
            self.target_xyz[0] -= self.pos_step
            moved = True
        elif key == "a":
            self.target_xyz[1] += self.pos_step
            moved = True
        elif key == "d":
            self.target_xyz[1] -= self.pos_step
            moved = True
        elif key == "r":
            self.target_xyz[2] += self.pos_step
            moved = True
        elif key == "f":
            self.target_xyz[2] -= self.pos_step
            moved = True
        elif key == "u":
            self.target_rpy[0] -= self.rpy_step
            moved = True
        elif key == "o":
            self.target_rpy[0] += self.rpy_step
            moved = True
        elif key == "i":
            self.target_rpy[1] += self.rpy_step
            moved = True
        elif key == "k":
            self.target_rpy[1] -= self.rpy_step
            moved = True
        elif key == "j":
            self.target_rpy[2] += self.rpy_step
            moved = True
        elif key == "l":
            self.target_rpy[2] -= self.rpy_step
            moved = True
        elif key == "[":
            self.gripper = max(self.args.gripper_min, self.gripper - self.args.gripper_step)
            moved = True
        elif key == "]":
            self.gripper = min(self.args.gripper_max, self.gripper + self.args.gripper_step)
            moved = True

        if moved:
            self.solve_and_publish_target()
        return "none"

    def status_line(self, point_idx, arm):
        xyz = self.target_xyz.round(4).tolist()
        rpy_deg = np.rad2deg(self.target_rpy).round(1).tolist()
        print(
            f"\r[point {point_idx + 1}/{self.args.num_points}] "
            f"{arm.upper():5s} xyz={xyz} rpy_deg={rpy_deg} "
            f"step={self.pos_step * 1000:.0f}mm "
            f"rstep={math.degrees(self.rpy_step):.1f}deg "
            "SPACE=record q=quit ?=help",
            end="",
            flush=True,
        )

    def collect(self):
        print("=" * 78)
        print("[ctrl] One-terminal touch calibration")
        print("[ctrl] Start piper launch with mode:=1 auto_enable:=true")
        print(f"[ctrl] points={self.args.num_points}, tcp_offset={self.args.tcp_offset}")
        print("=" * 78)
        print("[ctrl] waiting for joint and end_pose feedback...")
        if not self.wait_feedback():
            raise SystemExit("[ctrl] timed out. Check piper launch and topics.")

        self.print_help()
        input("[ctrl] Press ENTER to begin. Keep one hand near emergency stop/disable.")

        with RawKeyboard() as kb:
            for point_idx in range(self.args.num_points):
                print("\n" + "-" * 78)
                print(f"[ctrl] Physical point {point_idx + 1}/{self.args.num_points}")
                for arm in ARMS:
                    self.set_active_arm_from_feedback(arm)
                    print(f"\n[ctrl] Active arm: {arm.upper()}. Jog the sharp tip to the point.")
                    last_status = 0.0
                    while not rospy.is_shutdown():
                        now = time.time()
                        if now - last_status > 0.25:
                            self.status_line(point_idx, arm)
                            last_status = now
                        key = kb.read_key(timeout=0.05)
                        action = self.handle_key(key)
                        if action == "quit":
                            raise KeyboardInterrupt
                        if action == "record":
                            mean, std = self.sample_tcp(arm)
                            self.points[arm].append(mean)
                            print(
                                f"\n[ctrl] recorded {arm:5s}: "
                                f"xyz={mean.round(6).tolist()} "
                                f"std_mm={(std * 1000.0).round(2).tolist()}"
                            )
                            print("[ctrl] resetting this arm before advancing...")
                            self.reset_arm(arm)
                            break
        return self.points

    def solve(self):
        mid = np.asarray(self.points["mid"], dtype=float)
        left = np.asarray(self.points["left"], dtype=float)
        right = np.asarray(self.points["right"], dtype=float)
        R_l, t_l, e_l = fit_rigid_transform(left, mid)
        R_r, t_r, e_r = fit_rigid_transform(right, mid)
        result = {
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "world_frame": "mid_base",
            "num_points": int(self.args.num_points),
            "tcp_offset": [float(x) for x in self.args.tcp_offset],
            "points": {
                arm: [[float(x) for x in p] for p in self.points[arm]]
                for arm in ARMS
            },
            "transforms": {
                "mid": transform_to_dict(np.eye(3), np.zeros(3)),
                "left": transform_to_dict(R_l, t_l),
                "right": transform_to_dict(R_r, t_r),
            },
            "errors_m": {
                "left_to_mid": [float(x) for x in e_l],
                "right_to_mid": [float(x) for x in e_r],
            },
            "summary_m": {
                "left_to_mid": {
                    "mean": float(e_l.mean()),
                    "rms": float(math.sqrt(np.mean(e_l ** 2))),
                    "max": float(e_l.max()),
                },
                "right_to_mid": {
                    "mean": float(e_r.mean()),
                    "rms": float(math.sqrt(np.mean(e_r ** 2))),
                    "max": float(e_r.max()),
                },
            },
        }
        return result

    def save(self, result):
        out_dir = os.path.abspath(self.args.output_dir)
        os.makedirs(out_dir, exist_ok=True)
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base = os.path.join(out_dir, f"arm_extrinsics_controlled_touch_{stamp}")
        json_path = base + ".json"
        yaml_path = base + ".yaml"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2, sort_keys=True)
        write_yaml(yaml_path, result)
        return json_path, yaml_path

    def run(self):
        self.collect()
        result = self.solve()
        json_path, yaml_path = self.save(result)
        print("\n" + "=" * 78)
        print("[ctrl] Calibration finished")
        for arm in ("left", "right"):
            tr = result["transforms"][arm]
            stats = result["summary_m"][f"{arm}_to_mid"]
            print(f"\n{arm.upper()} -> MID")
            print(f"  xyz = {np.asarray(tr['xyz']).round(6).tolist()} m")
            print(f"  rpy = {np.asarray(tr['rpy']).round(6).tolist()} rad")
            print(
                f"  error mean={stats['mean'] * 1000.0:.2f} mm, "
                f"rms={stats['rms'] * 1000.0:.2f} mm, "
                f"max={stats['max'] * 1000.0:.2f} mm"
            )
        print("\nSaved:")
        print(f"  {json_path}")
        print(f"  {yaml_path}")
        print("=" * 78)


def get_args():
    default_urdf = (
        "/home/agilex/cobot_magic/Piper_ros_private-ros-noetic/src/piper_description/urdf/"
        "piper_description_new.urdf"
    )
    p = argparse.ArgumentParser(description="One-terminal controlled 3-arm touch calibration.")
    p.add_argument("--num_points", type=int, default=10)
    p.add_argument("--urdf", type=str, default=default_urdf)
    p.add_argument(
        "--tcp_offset",
        nargs=3,
        type=float,
        default=[0.0, 0.0, 0.0],
        metavar=("X", "Y", "Z"),
        help="Tip offset from end_pose frame, in end_pose local frame, meters.",
    )
    p.add_argument("--pos_step", type=float, default=0.005)
    p.add_argument("--rpy_step", type=float, default=math.radians(1.0))
    p.add_argument("--gripper", type=float, default=INITIAL_GRIPPER)
    p.add_argument("--gripper_step", type=float, default=0.005)
    p.add_argument("--gripper_min", type=float, default=0.0)
    p.add_argument("--gripper_max", type=float, default=0.1)
    p.add_argument("--samples", type=int, default=20)
    p.add_argument("--sample_dt", type=float, default=0.01)
    p.add_argument("--ramp_speed_rad_s", type=float, default=0.15)
    p.add_argument("--min_ramp_sec", type=float, default=2.0)
    p.add_argument("--hold_sec", type=float, default=0.5)
    p.add_argument("--hz", type=float, default=30.0)
    p.add_argument("--feedback_wait", type=float, default=10.0)
    p.add_argument(
        "--output_dir",
        type=str,
        default="/home/agilex/cobot_magic/aloha-devel/Piper-AVP-Teleop/teleop/calibration_outputs",
    )
    return p.parse_args()


def main():
    args = get_args()
    if args.num_points < 3:
        raise SystemExit("--num_points must be >= 3")
    try:
        ControlledTouchCalibrator(args).run()
    except KeyboardInterrupt:
        print("\n[ctrl] stopped.")


if __name__ == "__main__":
    main()
