#!/usr/bin/env python3
"""
Touch-point calibration for three Piper arms.

The operator manually moves each arm so its end-effector center touches the same
physical point. For each point, record MID, LEFT, and RIGHT TCP positions.
The script then fits rigid transforms into the MID arm base frame:

    p_mid ~= R_left_to_mid  @ p_left  + t_left_to_mid
    p_mid ~= R_right_to_mid @ p_right + t_right_to_mid

No robot commands are published by this script. It only subscribes to feedback.
"""
import argparse
import json
import math
import os
import time
from datetime import datetime

import numpy as np
import rospy
from geometry_msgs.msg import PoseStamped
from tf.transformations import euler_from_matrix, quaternion_matrix


ARMS = ("mid", "left", "right")


def pose_to_tcp_xyz(msg, tcp_offset):
    p = msg.pose.position
    q = msg.pose.orientation
    T = quaternion_matrix([q.x, q.y, q.z, q.w])
    xyz = np.array([p.x, p.y, p.z], dtype=float)
    return xyz + T[:3, :3] @ np.asarray(tcp_offset, dtype=float)


def fit_rigid_transform(src_points, dst_points):
    """Return R, t, errors for dst ~= R @ src + t."""
    src = np.asarray(src_points, dtype=float)
    dst = np.asarray(dst_points, dtype=float)
    if src.shape != dst.shape or src.ndim != 2 or src.shape[1] != 3:
        raise ValueError("src/dst must both be shaped (N, 3)")
    if src.shape[0] < 3:
        raise ValueError("at least 3 points are required")

    src_centroid = src.mean(axis=0)
    dst_centroid = dst.mean(axis=0)
    X = src - src_centroid
    Y = dst - dst_centroid

    H = X.T @ Y
    U, _, Vt = np.linalg.svd(H)
    R = Vt.T @ U.T
    if np.linalg.det(R) < 0.0:
        Vt[-1, :] *= -1.0
        R = Vt.T @ U.T
    t = dst_centroid - R @ src_centroid

    pred = (R @ src.T).T + t
    errors = np.linalg.norm(pred - dst, axis=1)
    return R, t, errors


def transform_to_dict(R, t):
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = t
    rpy = np.array(euler_from_matrix(T), dtype=float)
    return {
        "xyz": [float(x) for x in t],
        "rpy": [float(x) for x in rpy],
        "matrix": [[float(x) for x in row] for row in T],
    }


def write_yaml(path, result):
    def vec(v):
        return "[" + ", ".join(f"{float(x):.9f}" for x in v) + "]"

    lines = [
        "# Generated by calibrate_3arm_touch_points.py",
        f"created_at: {result['created_at']}",
        "world_frame: mid_base",
        "source: touch_point_svd",
        f"num_points: {result['num_points']}",
        f"tcp_offset: {vec(result['tcp_offset'])}",
        "transforms:",
    ]
    for arm in ("mid", "left", "right"):
        tr = result["transforms"][arm]
        lines += [
            f"  {arm}:",
            f"    parent: mid_base",
            f"    child: {arm}_base",
            f"    xyz: {vec(tr['xyz'])}",
            f"    rpy: {vec(tr['rpy'])}",
            "    matrix:",
        ]
        for row in tr["matrix"]:
            lines.append(f"      - {vec(row)}")
    lines += [
        "errors_m:",
        f"  left_to_mid: {vec(result['errors_m']['left_to_mid'])}",
        f"  right_to_mid: {vec(result['errors_m']['right_to_mid'])}",
        "summary_m:",
    ]
    for key, stats in result["summary_m"].items():
        lines += [
            f"  {key}:",
            f"    mean: {stats['mean']:.9f}",
            f"    max: {stats['max']:.9f}",
            f"    rms: {stats['rms']:.9f}",
        ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


class TouchCalibrator:
    def __init__(self, args):
        self.args = args
        self.latest_pose = {arm: None for arm in ARMS}
        rospy.init_node("calibrate_3arm_touch_points", anonymous=True)
        for arm in ARMS:
            rospy.Subscriber(
                f"/puppet/end_pose_{arm}",
                PoseStamped,
                self._make_pose_cb(arm),
                queue_size=50,
                tcp_nodelay=True,
            )

    def _make_pose_cb(self, arm):
        def cb(msg):
            self.latest_pose[arm] = msg
        return cb

    def wait_feedback(self):
        deadline = rospy.Time.now() + rospy.Duration(self.args.feedback_wait)
        rate = rospy.Rate(20)
        while not rospy.is_shutdown():
            if all(self.latest_pose[arm] is not None for arm in ARMS):
                return True
            if rospy.Time.now() > deadline:
                return False
            rate.sleep()
        return False

    def sample_tcp(self, arm):
        samples = []
        for _ in range(self.args.samples):
            msg = self.latest_pose[arm]
            if msg is not None:
                samples.append(pose_to_tcp_xyz(msg, self.args.tcp_offset))
            time.sleep(self.args.sample_dt)
        if not samples:
            raise RuntimeError(f"no pose samples for {arm}")
        arr = np.vstack(samples)
        return arr.mean(axis=0), arr.std(axis=0)

    def collect(self):
        points = {arm: [] for arm in ARMS}
        print("=" * 72)
        print("[calib] Touch-point calibration. This script records feedback only.")
        print("[calib] world frame = MID arm base_link")
        print(f"[calib] points = {self.args.num_points}")
        print(f"[calib] tcp_offset = {np.asarray(self.args.tcp_offset).round(4).tolist()} m")
        print("=" * 72)
        print("[calib] waiting for /puppet/end_pose_<arm> feedback...")
        if not self.wait_feedback():
            raise SystemExit("[calib] timed out. Are all piper nodes running?")

        input(
            "\n[calib] Move each arm by hand/teach mode. Use the end-effector "
            "center as the contact point. Press ENTER when ready."
        )

        total_needed = self.args.num_points * len(ARMS)
        while sum(len(points[arm]) for arm in ARMS) < total_needed:
            total_done = sum(len(points[arm]) for arm in ARMS)
            idx = total_done // len(ARMS)
            arm = ARMS[total_done % len(ARMS)]

            if total_done % len(ARMS) == 0:
                print("\n" + "-" * 72)
                print(f"[calib] POINT {idx + 1}/{self.args.num_points}")
                print("[calib] Use a physical point that all 3 arms can touch.")

            cmd = input(
                f"[calib] Move {arm.upper()} end-effector center to this SAME point.\n"
                "        ENTER=record, u=undo last record, q=quit: "
            ).strip().lower()

            if cmd == "q":
                raise KeyboardInterrupt
            if cmd == "u":
                if total_done == 0:
                    print("[calib] nothing to undo yet.")
                    continue
                last_total = total_done - 1
                last_idx = last_total // len(ARMS)
                last_arm = ARMS[last_total % len(ARMS)]
                removed = points[last_arm].pop()
                print(
                    f"[calib] undone POINT {last_idx + 1}/{self.args.num_points} "
                    f"{last_arm.upper()}: xyz={np.asarray(removed).round(5).tolist()}"
                )
                continue
            if cmd:
                print("[calib] unknown command. Use ENTER, u, or q.")
                continue

            mean, std = self.sample_tcp(arm)
            points[arm].append(mean)
            print(
                f"[calib] recorded POINT {idx + 1}/{self.args.num_points} {arm:5s}: "
                f"xyz={mean.round(5).tolist()}  "
                f"sample_std_mm={(std * 1000.0).round(2).tolist()}"
            )
            if arm == ARMS[-1]:
                print("[calib] Point recorded. Move to a different physical point next.")
        return points

    def solve(self, points):
        counts = {arm: len(points[arm]) for arm in ARMS}
        if len(set(counts.values())) != 1:
            raise ValueError(f"arm point counts are not aligned: {counts}")
        mid = np.asarray(points["mid"], dtype=float)
        left = np.asarray(points["left"], dtype=float)
        right = np.asarray(points["right"], dtype=float)

        R_l, t_l, e_l = fit_rigid_transform(left, mid)
        R_r, t_r, e_r = fit_rigid_transform(right, mid)

        identity = np.eye(3)
        zeros = np.zeros(3)
        result = {
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "world_frame": "mid_base",
            "num_points": int(self.args.num_points),
            "tcp_offset": [float(x) for x in self.args.tcp_offset],
            "points": {
                arm: [[float(x) for x in p] for p in points[arm]]
                for arm in ARMS
            },
            "transforms": {
                "mid": transform_to_dict(identity, zeros),
                "left": transform_to_dict(R_l, t_l),
                "right": transform_to_dict(R_r, t_r),
            },
            "errors_m": {
                "left_to_mid": [float(x) for x in e_l],
                "right_to_mid": [float(x) for x in e_r],
            },
            "summary_m": {
                "left_to_mid": {
                    "mean": float(e_l.mean()),
                    "max": float(e_l.max()),
                    "rms": float(math.sqrt(np.mean(e_l ** 2))),
                },
                "right_to_mid": {
                    "mean": float(e_r.mean()),
                    "max": float(e_r.max()),
                    "rms": float(math.sqrt(np.mean(e_r ** 2))),
                },
            },
        }
        return result

    def save(self, result):
        out_dir = os.path.abspath(self.args.output_dir)
        os.makedirs(out_dir, exist_ok=True)
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base = os.path.join(out_dir, f"arm_extrinsics_touch_{stamp}")
        json_path = base + ".json"
        yaml_path = base + ".yaml"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2, sort_keys=True)
        write_yaml(yaml_path, result)
        return json_path, yaml_path

    def run(self):
        points = self.collect()
        result = self.solve(points)
        json_path, yaml_path = self.save(result)

        print("\n" + "=" * 72)
        print("[calib] Calibration result: transforms into MID base frame")
        for arm in ("left", "right"):
            tr = result["transforms"][arm]
            xyz = np.asarray(tr["xyz"])
            rpy = np.asarray(tr["rpy"])
            stats = result["summary_m"][f"{arm}_to_mid"]
            print(f"\n[calib] {arm.upper()} -> MID")
            print(f"  xyz = {xyz.round(6).tolist()} m")
            print(f"  rpy = {rpy.round(6).tolist()} rad")
            print(
                "  error = "
                f"mean {stats['mean'] * 1000.0:.2f} mm, "
                f"rms {stats['rms'] * 1000.0:.2f} mm, "
                f"max {stats['max'] * 1000.0:.2f} mm"
            )
        print("\n[calib] saved:")
        print(f"  {json_path}")
        print(f"  {yaml_path}")
        print("=" * 72)


def get_args():
    p = argparse.ArgumentParser(description="Calibrate 3-arm base extrinsics from touch points.")
    p.add_argument("--num_points", type=int, default=10)
    p.add_argument(
        "--tcp_offset",
        nargs=3,
        type=float,
        default=[0.0, 0.0, 0.0],
        metavar=("X", "Y", "Z"),
        help="Offset from /puppet/end_pose frame origin to the physical contact point, "
             "expressed in that end-pose local frame, meters. Default 0 0 0, which "
             "means using the end-effector center directly.",
    )
    p.add_argument("--samples", type=int, default=20)
    p.add_argument("--sample_dt", type=float, default=0.01)
    p.add_argument("--feedback_wait", type=float, default=10.0)
    p.add_argument(
        "--output_dir",
        type=str,
        default="/home/agilex/cobot_magic/aloha-devel/Piper-AVP-Teleop/teleop/calibration_outputs",
    )
    return p.parse_args()


def main():
    args = get_args()
    if args.num_points < 3:
        raise SystemExit("--num_points must be >= 3")
    try:
        TouchCalibrator(args).run()
    except KeyboardInterrupt:
        print("\n[calib] stopped.")


if __name__ == "__main__":
    main()
